CV_Predictor/urls.py
from django.urls import path
from . import views

app_name = "CV_Predictor"
urlpatterns = [
    path("", views.index, name="index"),
]

MicrosoftHack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('CV_Predictor/', include("CV_Predictor.urls"))
]

CV_Predictor/models.py
from django.db import models

# Create your models here.

CV_Predictor/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms

# Create your views here.

def index(request):
    # Check if method is POST
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewTaskForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            task = form.cleaned_data["task"]

        return HttpResponse(task)
    else:
        return render(request, "CV_Predictor/index.html", {
            "form": NewTaskForm()
        })



class NewTaskForm(forms.Form):
    task = forms.FileField(label="PDF File:")

CV_Predictor/templates/CV_Predictor/index.html
{% load static %}   
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>CV Predictor FrontRunner</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
        
        <link rel="stylesheet" href="{% static 'CV_Predictor/styles.css' %}">
       

       
        
    </head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="Form">
                
                <h2>Upload</h2>
                
                <form action="{% url 'CV_Predictor:index' %}" method="post">
                    {% csrf_token %}
           
                    {{ form }}
                        
                    <!-- <div class="Submit"><button type="submit" >Submit</button></div> -->
                    <input type="submit">
            
                </form>
                </div>
            </div>
            <div class="col-sm-4"></div>
        </div>     
    </div>

   
    
</body>
</html>